on:
  push:
    tags: 
      - 'v-*'
jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: pull and build on remote server
        uses: appleboy/ssh-action@master
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          envs: MONGO_USER,MONGO_PASS
          script: |
            cd /var/www/tams-club-cal
            git pull
            cd client
            yarn install
            cd ../server
            yarn install
            echo "MONGO_USER=$MONGO_USER" >| .env
            echo "MONGO_PASS=$MONGO_PASS" >> .env
            echo "{\"backend\":\"https://pr.tams.club\"}" >| ../client/src/files/config.json
            cd ../client
            yarn build
            pm2 restart tams-club-cal-server
